export default {  
	hello: 'Привет',
	pluse_images:'картинок',
	amd:'драм',
	checkout:'Заказать за ',
	order:'Заказать',
	size:'Размер',
	price:'Цена',
	copy:'экземпляр',
	new_order:'Новый заказ',
	main_header:'Онлайн фотосервис',
	main_tab:'Плавная',
	history_tab:'История',
	email:'почта',
	password:'пороль',
	forget_password:'Забили пороль?',
	sign_in:'Вайти',
	or_sign_in_social:'или вайдите через соцсети',
	sign_in_your_account:'Вайдите ваш профиль',
	have_not_account:'Если нету профиля, то зарегистрируйтесь',
	user_name:'Имя',
	i_read_and_agree:'Я прочитал и согласен с',
	terms_and_conditions:'условиями пользовательского соглашения',
	sign_up:'Регистрация',
	register_using_social:'Или зарегистрируйтесь через соцсети',
	already_have_account:'Уже имеете профиль? Войти',
	delivery:'Надо доставка',
	address:'Адресс',
	comment:'Коментарии',
	select:'Выбрать',
	history:'История',
	count:'количестна',
	number_of_order:'Номер заказа',
	status:'Статус',
	status_new:"Новый",
	addresses:"Адресса достсвки",
	benefit:'Получитель',
	city:'город',
	new_address:'Новый Адресс',
	add_new_address:"Добавить новый заказ",
	city_gyumri:'Гюмри',
	city_yerevan:'Ереван',
	address_and_benefit:'адресс/получатель',
	dilevery_cost:'цена за даставкю'
  };